PRODUCT_PROPERTY_OVERRIDES += \
    rild.libpath=/vendor/lib/libril-qc-qmi-1.so \
    persist.radio.add_power_save=1 \
    persist.radio.apm_sim_not_pwdn=1 \
    persist.radio.no_wait_for_card=1 \
    persist.data.netmgrd.qos.enable=false \
    persist.qcril.disable_retry=true \
    persist.telephony.oosisdc=false \
    ro.use_data_netmgrd=true \
    ro.com.android.mobiledata=false \
    ril.subscription.types=NV,RUIM
